apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: kb13bo467-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/chetna14manku_org/rhtap-qe-java-quarkus:github-384ebb848625d0fc3ac56610c3b37608d2dfb66a
          name: container-image
